name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Awaiting Changes"
